name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./gen
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
        working-directory: ${{ secrets.working-directory }}
      - run: npm publish
        working-directory: ${{ secrets.working-directory }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
